export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const PROFILEID_REQUEST = "PROFILEID_REQUEST";
export const PROFILEID_SUCCESS = "PROFILEID_SUCCESS";
export const PROFILEID_FAILURE = "PROFILEID_FAILURE";